language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:1.0.0"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
